version: '3.9'

services:
  app:
    build: 
      context: ./workout-api/
      dockerfile: Dockerfile
    container_name: Workout-Api
    ports:
      - "8000:8000"

    depends_on:
      - postgresql
  postgresql:
    image: postgres:latest
    container_name: PostgreSQL
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: workoutdb
    # ports:
    #   - 5151:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: PGadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: name@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    
    logging:
      driver: "none"

    depends_on:
      - postgresql
